name: CI

on: [push, pull_request]

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: npm install
        run: npm install
      - name: npm test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: npm install
        run: npm install
      - name: npm test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test2
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: npm install
        run: npm install
      - name: npm test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: npm install
        run: npm install
      - name: npm test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test4
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
